# fly.toml
app = "nfabysj"  # Change this to a unique name
primary_region = "syd"  # Sydney region (closest to Melbourne)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8501"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.ports]]
  port = 80
  handlers = ["http"]

[[http_service.ports]]
  port = 443
  handlers = ["tls", "http"]

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20
